import { getWorldMapCellKey, type WorldMapLayout } from "../../data/worldMapLayout";
import { cloneLayout } from "../mapShared";
import { type MapEditorState } from "./mapEditorReducer";

export function createInitialMapEditorState(initialLayout: WorldMapLayout, initialJsonBuffer: string): MapEditorState {
  return {
    layout: cloneLayout(initialLayout),
    layerVisibility: { ...initialLayout.defaultLayers },
    selectedCellKey: getWorldMapCellKey({ x: 13, y: 11 }),
    selectedRouteId: initialLayout.paths[0]?.id ?? "",
    routeDrawActive: false,
    selectedAreaCellKeys: [],
    activeTool: "inspect",
    jsonBuffer: initialJsonBuffer,
    jsonError: null,
    openPanels: {
      legend: true,
      layers: true,
      json: false
    },
    selectedLoreCityId: "",
    selectedLoreLocationId: "",
    draftCityName: "",
    selectedGovernanceTerritoryId: "",
    selectedGovernanceRegionId: "",
    selectedGeographicZoneId: "",
    draftTerritoryId: "",
    draftTerritoryColor: "#d7b56d",
    draftRegionId: "",
    draftRegionColor: "#5a7d8f",
    draftGovernanceId: "",
    draftGovernanceColor: "#b890d9",
    draftGovernanceCapitalCityId: "",
    draftGeographicZoneId: "",
    draftGeographicZoneLabel: "",
    draftGeographicZoneColor: "#5fa8d3",
    draftGeographicZoneBorderColor: "#5fa8d3",
    draftGeographicZoneBorderWidth: "1.6",
    draftGeographicZoneBorderDashArray: "5 4",
    draftGeographicZoneKind: "natural",
    selectedGovernanceLoreId: "",
    selectedGeographicZoneLoreId: "",
    hexModalPosition: { x: 420, y: 20 },
    customGeographies: [...(initialLayout.editorPresets?.customGeographies ?? [])],
    customTags: [...(initialLayout.editorPresets?.customTags ?? [])],
    draftGeographyName: "",
    draftGeographyColor: "#5a7d8f",
    draftGeographySurface: "land",
    draftGeographyDifficulty: "5",
    draftTagName: "",
    draftTagColor: "#5fa8d3",
    selectedSimulationFactionId: "",
    draftSimulationFactionId: "",
    draftSimulationFactionLabel: "",
    draftSimulationFactionType: "faction",
    draftSimulationFactionColor: "#c96f4a",
    draftSimulationRelationTargetFactionId: "",
    draftSimulationRelationStatus: "neutral",
    selectedSimulationObjectiveId: "",
    draftSimulationObjectiveId: "",
    draftSimulationObjectiveLabel: "",
    draftSimulationObjectiveCategory: "extend_influence",
    selectedSimulationMobileActorId: "",
    draftSimulationMobileActorId: "",
    draftSimulationMobileActorLabel: "",
    draftSimulationMobileActorType: "caravan",
    draftSimulationMobileActorColor: "#77b3d4",
    pendingGeographyId: "",
    pendingReliefElevation: "",
    pendingTagIds: [],
    persistenceState: "idle",
    lastSavedLayoutJson: initialJsonBuffer
  };
}
